<?php

use Illuminate\Database\Seeder;

class ColoniesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colonies = [
            ['id' => 1, 'name' => 'Ampliación Granjas de Guadalupe', 'slug' => 'ampliacion-granjas-de-guadalupe', 'state' => '1', 'zip_id' => 1],
            ['id' => 2, 'name' => 'Ampliación Vista Hermosa', 'slug' => 'ampliacion-vista-hermosa', 'state' => '1', 'zip_id' => 2],
            ['id' => 3, 'name' => 'Aquiles Córdoba Morán', 'slug' => 'ampliacion-cordoba-moran', 'state' => '1', 'zip_id' => 3],
            ['id' => 4, 'name' => 'Arcoiris', 'slug' => 'arcoiris', 'state' => '1', 'zip_id' => 4],
            ['id' => 5, 'name' => 'Azotlán Parte Alta', 'slug' => 'azotlan-parte-alta', 'state' => '1', 'zip_id' => 5],
            ['id' => 6, 'name' => 'Azotlán Parte Baja', 'slug' => 'azotlan-parte-baja', 'state' => '1', 'zip_id' => 5],
            ['id' => 7, 'name' => 'Barrón', 'slug' => 'barron', 'state' => '1', 'zip_id' => 6],
            ['id' => 8, 'name' => 'Benito Juárez', 'slug' => 'benito-juarez', 'state' => '1', 'zip_id' => 7],
            ['id' => 9, 'name' => 'Benito Juárez 1a. Sección', 'slug' => 'benito-juarez-1a-seccion', 'state' => '1', 'zip_id' => 8],
            ['id' => 10, 'name' => 'Benito Juárez Barrón', 'slug' => 'benito-juarez-barron', 'state' => '1', 'zip_id' => 9],
            ['id' => 11, 'name' => 'Bosques de la Colmena', 'slug' => 'bosques-de-la-colmena', 'state' => '1', 'zip_id' => 10],
            ['id' => 12, 'name' => 'Buenavista', 'slug' => 'buenavista', 'state' => '1', 'zip_id' => 2],
            ['id' => 13, 'name' => 'Bulevares del Lago', 'slug' => 'bulevares-del-lago', 'state' => '1', 'zip_id' => 11],
            ['id' => 14, 'name' => 'Caja de Agua', 'slug' => 'caja-de-agua', 'state' => '1', 'zip_id' => 12],
            ['id' => 15, 'name' => 'Campestre Liberación', 'slug' => 'campestre-liberacion', 'state' => '1', 'zip_id' => 11],
            ['id' => 16, 'name' => 'Cantaros I', 'slug' => 'cantaros-i', 'state' => '1', 'zip_id' => 13],
            ['id' => 17, 'name' => 'Cantaros II', 'slug' => 'cantaros-ii', 'state' => '1', 'zip_id' => 13],
            ['id' => 18, 'name' => 'Cantaros III', 'slug' => 'cantaros-iii', 'state' => '1', 'zip_id' => 14],
            ['id' => 19, 'name' => 'Cinco de Febrero', 'slug' => 'cinco-de-febrero', 'state' => '1', 'zip_id' => 15],
            ['id' => 20, 'name' => 'Ciudad Campestre', 'slug' => 'ciudad-campestre', 'state' => '1', 'zip_id' => 16],
            ['id' => 21, 'name' => 'Clara Córdova Morán', 'slug' => 'clara-cordova-moran', 'state' => '1', 'zip_id' => 1],
            ['id' => 22, 'name' => 'Colonial del Lago', 'slug' => 'colonial-del-lago', 'state' => '1', 'zip_id' => 10],
            ['id' => 23, 'name' => 'Cuarto Barrio Cahuacán', 'slug' => 'cuarto-barrio-cahuacan', 'state' => '1', 'zip_id' => 17],
            ['id' => 24, 'name' => 'Cumbres', 'slug' => 'cumbres', 'state' => '1', 'zip_id' => 14],
            ['id' => 25, 'name' => 'De la Luz', 'slug' => 'de-la-luz', 'state' => '1', 'zip_id' => 18],
            ['id' => 26, 'name' => 'El Esclavo', 'slug' => 'el-esclavo', 'state' => '1', 'zip_id' => 18],
            ['id' => 27, 'name' => 'El Gavillero', 'slug' => 'el-gavillero', 'state' => '1', 'zip_id' => 19],
            ['id' => 28, 'name' => 'El Globo', 'slug' => 'el-globo', 'state' => '1', 'zip_id' => 20],
            ['id' => 29, 'name' => 'El Mirador', 'slug' => 'el-mirador', 'state' => '1', 'zip_id' => 18],
            ['id' => 30, 'name' => 'El Tanque', 'slug' => 'el-tanque', 'state' => '1', 'zip_id' => 21],
            ['id' => 31, 'name' => 'El Trafico', 'slug' => 'el-trafico', 'state' => '1', 'zip_id' => 16],
            ['id' => 32, 'name' => 'Francisco I. Madero 1a. Sección', 'slug' => 'francisco-i-madero-1a-seccion', 'state' => '1', 'zip_id' => 4],
            ['id' => 33, 'name' => 'Francisco I. Madero Sección 20', 'slug' => 'francisco-i-madero-seccion-20', 'state' => '1', 'zip_id' => 4],
            ['id' => 34, 'name' => 'Francisco Sarabia 1a. Sección', 'slug' => 'francisco-sarabia-1a-seccion', 'state' => '1', 'zip_id' => 11],
            ['id' => 35, 'name' => 'Francisco Sarabia 2a. Sección', 'slug' => 'francisco-sarabia-2a-seccion', 'state' => '1', 'zip_id' => 11],
            ['id' => 36, 'name' => 'Fuentes de San José', 'slug' => 'fuentes-de-san-jose', 'state' => '1', 'zip_id' => 13],
            ['id' => 37, 'name' => 'Granjas de Guadalupe 1a. Sección', 'slug' => 'granjas-de-guadalupe-1a-seccion', 'state' => '1', 'zip_id' => 1],
            ['id' => 38, 'name' => 'Guadalupe', 'slug' => 'guadalupe', 'state' => '1', 'zip_id' => 22],
            ['id' => 39, 'name' => 'Guadalupe San Ildefonso', 'slug' => 'guadalupe-san-ildefonso', 'state' => '1', 'zip_id' => 15],
            ['id' => 40, 'name' => 'Hidalgo', 'slug' => 'hidalgo', 'state' => '1', 'zip_id' => 23],
            ['id' => 41, 'name' => 'Himno Nacional', 'slug' => 'himno-nacional', 'state' => '1', 'zip_id' => 16],
            ['id' => 42, 'name' => 'Ignacio Capetillo', 'slug' => 'ignacio-capetillo', 'state' => '1', 'zip_id' => 23],
            ['id' => 43, 'name' => 'Ignacio Zaragoza', 'slug' => 'ignacio-zaragoza', 'state' => '1', 'zip_id' => 24],
            ['id' => 44, 'name' => 'Independencia 1a. Sección', 'slug' => 'independencia-1a-seccion', 'state' => '1', 'zip_id' => 25],
            ['id' => 45, 'name' => 'Independencia 2a. Sección', 'slug' => 'independencia-2a-seccion', 'state' => '1', 'zip_id' => 25],
            ['id' => 46, 'name' => 'Jorge Jiménez Cantú', 'slug' => 'jorge-jimenez-cantu', 'state' => '1', 'zip_id' => 26],
            ['id' => 47, 'name' => 'Joya del Tejocote', 'slug' => 'joya-del-tejocote', 'state' => '1', 'zip_id' => 12],
            ['id' => 48, 'name' => 'La Colmena', 'slug' => 'la-colmena', 'state' => '1', 'zip_id' => 27],
            ['id' => 49, 'name' => 'La Concepción', 'slug' => 'la-concepcion', 'state' => '1', 'zip_id' => 28],
            ['id' => 50, 'name' => 'La Concepción', 'slug' => 'la-concepcion-0', 'state' => '1', 'zip_id' => 12],
            ['id' => 51, 'name' => 'La Estancia', 'slug' => 'la-estancia', 'state' => '1', 'zip_id' => 29],
            ['id' => 52, 'name' => 'Libertad 1a. Sección', 'slug' => 'libertad-1a-seccion', 'state' => '1', 'zip_id' => 3],
            ['id' => 53, 'name' => 'Libertad 2a. Sección', 'slug' => 'libertad-2a-seccion', 'state' => '1', 'zip_id' => 3],
            ['id' => 54, 'name' => 'Llano Grande', 'slug' => 'llano-grande', 'state' => '1', 'zip_id' => 21],
            ['id' => 55, 'name' => 'Loma de Chapultepec', 'slug' => 'loma-de-chapultepec', 'state' => '1', 'zip_id' => 17],
            ['id' => 56, 'name' => 'Loma de Guadalupe el Vidrio', 'slug' => 'loma-de-guadalupe-el-vidrio', 'state' => '1', 'zip_id' => 30],
            ['id' => 57, 'name' => 'Loma de la Cruz 1a. Sección', 'slug' => 'loma-de-la-cruz-1a-seccion', 'state' => '1', 'zip_id' => 27],
            ['id' => 58, 'name' => 'Loma de San José', 'slug' => 'loma-de-san-jose', 'state' => '1', 'zip_id' => 31],
            ['id' => 59, 'name' => 'Loma de San Miguel', 'slug' => 'loma-de-san-miguel', 'state' => '1', 'zip_id' => 30],
            ['id' => 60, 'name' => 'Loma del Río', 'slug' => 'loma-del-rio', 'state' => '1', 'zip_id' => 21],
            ['id' => 61, 'name' => 'Loma Larga', 'slug' => 'loma-larga', 'state' => '1', 'zip_id' => 19],
            ['id' => 62, 'name' => 'Lomas de Guadalupe', 'slug' => 'lomas-de-guadalupe', 'state' => '1', 'zip_id' => 5],
            ['id' => 63, 'name' => 'Lomas del Lago', 'slug' => 'lomas-del-lago', 'state' => '1', 'zip_id' => 10],
            ['id' => 64, 'name' => 'Los Manantiales', 'slug' => 'los-manantiales', 'state' => '1', 'zip_id' => 32],
            ['id' => 65, 'name' => 'Los Tubos', 'slug' => 'los-tubos', 'state' => '1', 'zip_id' => 12],
            ['id' => 66, 'name' => 'Mirador del Conde', 'slug' => 'mirador-del-conde', 'state' => '1', 'zip_id' => 4],
            ['id' => 67, 'name' => 'Miranda', 'slug' => 'miranda', 'state' => '1', 'zip_id' => 17],
            ['id' => 68, 'name' => 'Morelos', 'slug' => 'morelos', 'state' => '1', 'zip_id' => 31],
            ['id' => 69, 'name' => 'Paseo de San Carlos', 'slug' => 'paseo-de-san-carlos', 'state' => '1', 'zip_id' => 13],
            ['id' => 70, 'name' => 'Primer Barrio Cahuacan', 'slug' => 'primer-barrio-cahuacan', 'state' => '1', 'zip_id' => 17],
            ['id' => 71, 'name' => 'Progreso Industrial', 'slug' => 'progreso-industrial', 'state' => '1', 'zip_id' => 12],
            ['id' => 72, 'name' => 'Pueblo Nuevo', 'slug' => 'pueblo-nuevo', 'state' => '1', 'zip_id' => 18],
            ['id' => 73, 'name' => 'Pueblo Viejo', 'slug' => 'pueblo-viejo', 'state' => '1', 'zip_id' => 10],
            ['id' => 74, 'name' => 'Puentecillas Cahuacán', 'slug' => 'puentecillas-cahuacan', 'state' => '1', 'zip_id' => 17],
            ['id' => 75, 'name' => 'Puerto Magú', 'slug' => 'puerto-magu', 'state' => '1', 'zip_id' => 18],
            ['id' => 76, 'name' => 'Quinto Barrio Cahuacán', 'slug' => 'quinto-barrio-cahuacan', 'state' => '1', 'zip_id' => 17],
            ['id' => 77, 'name' => 'Ricardo Flores Magón', 'slug' => 'ricardo-flores-magon', 'state' => '1', 'zip_id' => 10],
            ['id' => 78, 'name' => 'San Carlos', 'slug' => 'san-carlos', 'state' => '1', 'zip_id' => 13],
            ['id' => 79, 'name' => 'San Francisco Magú', 'slug' => 'san-francisco-magu', 'state' => '1', 'zip_id' => 33],
            ['id' => 80, 'name' => 'San Ildefonso', 'slug' => 'san-ildefonso', 'state' => '1', 'zip_id' => 34],
            ['id' => 81, 'name' => 'San Isidro La Paz 1a. Sección', 'slug' => 'san-isidro-la-paz-1a-seccion', 'state' => '1', 'zip_id' => 35],
            ['id' => 82, 'name' => 'San Isidro La Paz 2a. Sección', 'slug' => 'san-isidro-la-paz-2a-seccion', 'state' => '1', 'zip_id' => 35],
            ['id' => 83, 'name' => 'San Isidro La Paz 3a. Sección', 'slug' => 'san-isidro-la-paz-3a-seccion', 'state' => '1', 'zip_id' => 35],
            ['id' => 84, 'name' => 'San José el Vidrio', 'slug' => 'san-jose-el-vidrio', 'state' => '1', 'zip_id' => 30],
            ['id' => 85, 'name' => 'San Juan', 'slug' => 'san-juan', 'state' => '1', 'zip_id' => 15],
            ['id' => 86, 'name' => 'San Juan de las Tablas', 'slug' => 'san-juan-de-las-tablas', 'state' => '1', 'zip_id' => 32],
            ['id' => 87, 'name' => 'San Juan Tlihuaca', 'slug' => 'san-juan-tlihuaca', 'state' => '1', 'zip_id' => 13],
            ['id' => 88, 'name' => 'San Marcos', 'slug' => 'san-marcos', 'state' => '1', 'zip_id' => 25],
            ['id' => 89, 'name' => 'San Miguel Hila', 'slug' => 'san-miguel-hila', 'state' => '1', 'zip_id' => 36],
            ['id' => 90, 'name' => 'San Pablo de la Cruz', 'slug' => 'san-pablo-de-la-cruz', 'state' => '1', 'zip_id' => 12],
            ['id' => 91, 'name' => 'Santa Anita', 'slug' => 'santa-anita', 'state' => '1', 'zip_id' => 23],
            ['id' => 92, 'name' => 'Santa Anita la Bolsa', 'slug' => 'santa-anita-la-bolsa', 'state' => '1', 'zip_id' => 14],
            ['id' => 93, 'name' => 'Santa María Magdalena Cahuacán', 'slug' => 'santa-maria-magdalena-cahuacan', 'state' => '1', 'zip_id' => 17],
            ['id' => 94, 'name' => 'Segundo Barrio Cahuacán', 'slug' => 'segundo-barrio-cahuacan', 'state' => '1', 'zip_id' => 17],
            ['id' => 95, 'name' => 'Sitio 217', 'slug' => 'sitio-217', 'state' => '1', 'zip_id' => 10],
            ['id' => 96, 'name' => 'Tercer Barrio Cahuacán', 'slug' => 'tercer-barrio-cahuacan', 'state' => '1', 'zip_id' => 17],
            ['id' => 97, 'name' => 'Torres Peregrina', 'slug' => 'torres-peregrina', 'state' => '1', 'zip_id' => 25],
            ['id' => 98, 'name' => 'Transfiguración', 'slug' => 'transfiguracion', 'state' => '1', 'zip_id' => 29],
            ['id' => 99, 'name' => 'Unidad Magisterial', 'slug' => 'unidad-magisterial', 'state' => '1', 'zip_id' => 13],
            ['id' => 100, 'name' => 'Veintidós de Febrero', 'slug' => 'veintidos-de-febrero', 'state' => '1', 'zip_id' => 16],
            ['id' => 101, 'name' => 'Vicente Guerrero 1a. Sección', 'slug' => 'vicente-guerrero-1a-seccion', 'state' => '1', 'zip_id' => 37],
            ['id' => 102, 'name' => 'Vicente Guerrero 2a. Sección', 'slug' => 'vicente-guerrero-2a-seccion', 'state' => '1', 'zip_id' => 37],
            ['id' => 103, 'name' => 'Vicente Guerrero Barrón', 'slug' => 'vicente-guerrero-barron', 'state' => '1', 'zip_id' => 38],
            ['id' => 104, 'name' => 'Villas del Bosque', 'slug' => 'villas-del-bosque', 'state' => '1', 'zip_id' => 12],
            ['id' => 105, 'name' => 'Vista Hermosa 1a. Sección', 'slug' => 'vista-hermosa-1a-seccion', 'state' => '1', 'zip_id' => 2],
            ['id' => 106, 'name' => 'Vista Hermosa 2a. Sección', 'slug' => 'vista-hermosa-2a-seccion', 'state' => '1', 'zip_id' => 2],
            ['id' => 107, 'name' => 'Vista Verde', 'slug' => 'vista-verde', 'state' => '1', 'zip_id' => 1],
            ['id' => 108, 'name' => 'Y Griega', 'slug' => 'y-griega', 'state' => '1', 'zip_id' => 12],
    	];
    	DB::table('colonies')->insert($colonies);
    }
}
